name: VirusTotal

on:
  release:
    types: [published]

jobs:
  build:
    name: VirusTotal Scan
    runs-on: ubuntu-latest

    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            .exe$
